
from typing import List, Optional, Dict, Any, Union
from pydantic import BaseModel, Field
from .taxonomy import IntentType, BehaviorSubIntent, ComplianceSubIntent

class IntentNode(BaseModel):
    """Represents a single intent in the dependency graph."""
    intent: str = Field(..., description="The primary or sub-intent (e.g., LOITERING, EEZ_VIOLATION)")
    priority: int = Field(..., description="Execution priority (lower executes first)")
    depends_on: Optional[List[str]] = Field(default=None, description="List of intents this node depends on")
    parameters: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Initial parameters specific to this intent")

class MultiIntentOutput(BaseModel):
    """Output from the Multi-Intent Extractor LLM."""
    intents: List[IntentNode]

class EntityContext(BaseModel):
    """Context-aware resolved entities."""
    mmsi: List[int] = Field(default_factory=list)
    imo: List[str] = Field(default_factory=list)
    vessel_name: List[str] = Field(default_factory=list)
    region: Optional[str] = None
    time_range: Optional[Dict[str, str]] = Field(
        None, description="Time range with start/end keys, e.g. {'start': '2025-01-01', 'end': '2025-01-02'}"
    )
    derived_entities: Optional[Dict[str, Any]] = Field(
        default_factory=dict, 
        description="Entities derived from previous steps, e.g., {'candidate_vessels': [123, 456]}"
    )

class QueryPlan(BaseModel):
    """Abstract query plan generated by the Planner LLM."""
    dataset: str
    filters: List[str]
    join_with_previous: bool = Field(False, description="Whether to join with results from the previous step")
    output_columns: Optional[List[str]] = None

class InvestigationResult(BaseModel):
    """Standardized result wrapper."""
    intent: str
    data: Any
    summary: str
    timestamp: str

class ToolCall(BaseModel):
    tool_name: str
    input_from: str
    arguments: Dict[str, Any]

class ToolDAG(BaseModel):
    tools: List[ToolCall]
